### ISSUE TITLE
MTOUCH: Error MT5212: Native linking failed, duplicate symbol

### ISSUE THREAD

**Issue by NVentimiglia** [dkornev/TwilioVoiceXamarinIOS#10]
Im getting 'duplicate symbol' errors when I build. These duplicate includes are from another package I am including. I have a few packages so isolating the other package is not a valid solution. The Xamarin forms suggest using the --registrar:static flag, and I am also including the --cxx flag. This does not help.

What is the next step in solving this problem ?

MTOUCH: Error MT5212: Native linking failed, duplicate symbol: ''_CRYPTO_memcmp''. (MT5212) (AgriSync.iOS)
clang: Error: linker command failed with exit code 1 (use -v to see invocation) (AgriSync.iOS)
MTOUCH: Error MT5213: Duplicate symbol in: obj/iPhone/Debug/device-builds/iphone7.2-12.4.5/mtouch-cache/libTwilioVoice.a(mem.o) (Location related to previous error) (MT5213) (AgriSync.iOS)
MTOUCH: Error MT5213: Duplicate symbol in: obj/iPhone/Debug/device-builds/iphone7.2-12.4.5/mtouch-cache/libcrypto.a(cryptlib.o) (Location related to previous error) (MT5213) (AgriSync.iOS)
MTOUCH: Error MT5212: Native linking failed, duplicate symbol: ''_OPENSSL_cleanse''. (MT5212) (AgriSync.iOS)
MTOUCH: Error MT5213: Duplicate symbol in: obj/iPhone/Debug/device-builds/iphone7.2-12.4.5/mtouch-cache/libTwilioVoice.a(mem.o) (Location related to previous error) (MT5213) (AgriSync.iOS)
MTOUCH: Error MT5213: Duplicate symbol in: obj/iPhone/Debug/device-builds/iphone7.2-12.4.5/mtouch-cache/libcrypto.a(mem_clr.o) (Location related to previous error) (MT5213) (AgriSync.iOS)
error MT5209: Error: 2 duplicate symbols for architecture arm64 (AgriSync.iOS) Native linking
MTOUCH: Error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -ObjC -ObjC -lc++ -lz (MT5201) (AgriSync.iOS)
MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (AgriSync.iOS

**Comment by dkornev** [comment]
There is no much information in the build logs. I don't think that I will be able to help you without having access to the code. Could you provide me the exact steps to reproduce the issue?

Have you tried to implement https://github.com/twilio/voice-quickstart-ios using this Xamarin binding? Have you had any issues?

**Comment by NVentimiglia** [comment]
The bindings work on its own, its a clash with another nuget. Let me get you repo stpes.

**Comment by NVentimiglia** [comment]
Solved by using this MTouch args
--registrar:static -cxx -gcc_flags -dead_strip
